#Scraper

In [ ]:
import requests
from bs4 import BeautifulSoup

In [ ]:
r=requests.get('https://www.property.com.mm/index.php/en')
c=r.content
c

b'<!DOCTYPE html>\n<html lang="en">\n  <head>  \n        <meta charset="utf-8">\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n    <meta name="viewport" content="width=device-width, initial-scale=1">  \n    <title>Property.com.mm | Buy, Sell, Rent, Lease - Homepage - Find Commercial Industrial Residential Real Estate Property House Condo Land Warehouse Factory in Yangon Myanmar</title>\n    <!-- Autocomplete css -->\n    <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css"> -->\n    <meta name="description" content="Property.com.mm makes your home searching in Myanmar a pleasant and expedited experience with thousands of listings with PICTURES and hundreds of agents in Yangon. Please call us now +95-09-440048448." />\n    <meta name="keywords" content="Property.com.mm" />\n    <meta name="author" content="" />\n\t<!-- <meta name="apple-itunes-app" content="app-id=544007664"> -->\n    <meta name="google-play-app" content="app-id=com.studioamk.pmm">\n        <meta property="og:image" content="https://www.property.com.mm/templates/bootstrap2-responsive/assets/img/logo-transparent-og.png" />\n        <!-- Favicon -->\n    <link rel="shortcut icon" href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/img/favicon.png" type="image/png" />\n\n    <!-- Font awesome -->\n    <link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/font-awesome.css" rel="stylesheet">\n    <!-- Bootstrap -->\n    <link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/bootstrap.css" rel="stylesheet">   \n    <!-- slick slider -->\n    <link rel="stylesheet" type="text/css" href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/slick.css">\n    <!-- price picker slider -->\n    <link rel="stylesheet" type="text/css" href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/nouislider.css">\n    <!-- Fancybox slider -->\n    <link rel="stylesheet" href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/jquery.fancybox.css" type="text/css" media="screen" /> \n    <!-- Theme color -->\n    <link id="switcher" href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/theme-color/default-theme.css" rel="stylesheet">     \n    <!-- blueimp gallery -->\n    <link rel="stylesheet" type="text/css" href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/blueimp-gallery.min.css">\n    <!-- Main style sheet -->\n    <link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/style.css" rel="stylesheet">    \n\n    <link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/example/skitter.css" type="text/css" media="all" rel="stylesheet" />\n    <!-- Google Font -->\n    <link href=\'https://fonts.googleapis.com/css?family=Vollkorn\' rel=\'stylesheet\' type=\'text/css\'>    \n    <link href=\'https://fonts.googleapis.com/css?family=Open+Sans\' rel=\'stylesheet\' type=\'text/css\'>\n    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n    <!-- jQuery library -->\n    <!-- Autocomplete js -->\n    <link rel="stylesheet" href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/jquery-ui.css">\n    <script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyBSQyHRnuihlx2LpGrYwEACNg65AdqLOzs&amp;libraries=places,geometry&amp;language=en"></script>\n    <script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/jquery.min.js"></script>   \n    <script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/jquery-ui.js"></script>\n    <link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/jquery.multiselect.css" rel="stylesheet" />\n    <script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/jquery.multiselect.js"></script>\n    <script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/blueimp-gallery.min.js"></script>\n    <script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/gmap3.js"></script>\n    <!-- <script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/example/jquery-2.1.1.min.js"></script> -->\n    <script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/example/jquery.easing.1.3.js"></script>\n    <script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/example/jquery.skitter.min.js"></script>\n    <script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/jquery.helpers.js"></script>\n    <!-- / Autocomplete js -->\n    <script>\n        var timerMap;\n        var ad_galleries;\n        var firstSet = false;\n        var mapRefresh = true;\n        var loadOnTab = false;\n        var zoomOnMapSearch = 9;\n        var clusterConfig = null;\n        var markerOptions = null;\n        var mapDisableAutoPan = false;\n        var mapStyle = null;\n        var rent_inc_id = \'55\';\n        var scrollWheelEnabled = false;\n        var myLocationEnabled = true;\n        var rectangleSearchEnabled = true;\n        var c_mapTypeId = "style1"; // google.maps.MapTypeId.ROADMAP;\n        // var c_mapTypeIds = ["style1",\n        //                     google.maps.MapTypeId.ROADMAP,\n        //                     google.maps.MapTypeId.HYBRID];\n\n        $(document).ready(function() {\n            $(\'.pagination.news a\').click(function () { \n                var page_num = $(this).attr(\'href\');\n                var n = page_num.lastIndexOf("/"); \n                page_num = page_num.substr(n+1);\n                $.post($(this).attr(\'href\'), {search: $(\'#search_showroom\').val()}, function(data){\n                    // $(\'.property_content_position\').html(data.print);\n                    document.querySelector(\'.property_content_position\').innerHTML = data.print;\n                    reloadElements();\n                }, "json");\n                \n                return false;\n            });\n            $("#txtgoto").keyup(function(event){\n\t\t\t\tif(event.keyCode == 13){\n\t\t\t\t\t var pageno = (parseInt($(this).val())-1)*9;\n                manualSearch(pageno);\n              return false;\n\t\t\t\t}\n               \n\t\t\t});\n        });\n        function manualSearch(v_pagenum, scroll_enabled, onlysave)\n        {\n            if (typeof scroll_enabled === \'undefined\') scroll_enabled = "#content";\n            if (typeof onlysave === \'undefined\') onlysave = false;\n            var v_order = $(\'.selectpicker-small\').val();\n            var v_view = $(\'.view-type.active\').attr(\'ref\');  \n            var data = {\n                order: v_order,\n                view: v_view,\n                page_num: v_pagenum\n            };\n            if($(\'#booking_date_from\').length > 0)\n            {\n                if($(\'#booking_date_from\').val() != \'\')\n                    data[\'v_booking_date_from\'] = $(\'#booking_date_from\').val();\n            }\n            \n            if($(\'#booking_date_to\').length > 0)\n            {\n                if($(\'#booking_date_to\').val() != \'\')\n                    data[\'v_booking_date_to\'] = $(\'#booking_date_to\').val();\n            }\n        }\n        function reloadElements()\n        {            \n            // $(\'.selectpicker-small\').selectpicker({\n            //     style: \'btn-default\'\n            // });\n            \n            // $(\'.selectpicker-small\').change(function() {\n            //     manualSearch(0);\n            //     return false;\n            // });\n            \n            // $(\'.view-type\').click(function () { \n            //   $(this).parent().find(\'.view-type\').removeClass("active");\n            //   $(this).addClass("active");\n            //   manualSearch(0);\n            //   return false;\n            // });\n            \n            // $(\'.pagination.properties a\').click(function () { \n            //   var page_num = $(this).attr(\'href\');\n            //   var n = page_num.lastIndexOf("/"); \n            //   page_num = page_num.substr(n+1);\n              \n            //   manualSearch(page_num);\n            //   return false;\n            // });\n            // $("#txtgoto").keyup(function(event){\n\t\t\t// \tif(event.keyCode == 13){\n\t\t\t// \t\t/*if($( ".pagination.properties .pagination li:first a").html() == \'&lt;\'  || $( ".pagination.properties .pagination li:last a").html() == \'&gt;\')\n\t\t\t// \t\t{\n\t\t\t// \t\t\tvar pageno = parseInt($(this).val())+1;\n\t\t\t// \t\t\tconsole.log(".pagination.properties .pagination li:nth-child("+pageno+") a");\n\t\t\t// \t\t\t$( ".pagination.properties .pagination li:nth-child("+pageno+") a" ).click();\n\t\t\t// \t\t}\n\t\t\t// \t\telse\n\t\t\t// \t\t{\n\t\t\t// \t\t\t$( ".pagination.properties .pagination li:nth-child("+$(this).val()+") a" ).click();\n\t\t\t// \t\t}\n\t\t\t// \t\t*/\n\t\t\t// \t\t var pageno = (parseInt($(this).val())-1)*9;\n            //     manualSearch(pageno);\n            //   return false;\n\t\t\t// \t}\n               \n\t\t\t// });\n            $(\'.pagination.news a\').click(function () { \n                var page_num = $(this).attr(\'href\');\n                var n = page_num.lastIndexOf("/"); \n                page_num = page_num.substr(n+1);\n                \n                $.post($(this).attr(\'href\'), {search: $(\'#search_showroom\').val()}, function(data){\n                    document.querySelector(\'.property_content_position\').innerHTML = data.print;\n                    reloadElements();\n                }, "json");\n                \n                return false;\n            });\n        }\n        function init_gmap_searchbox()\n        {\n            if( $(\'#pac-input\').length==0 || $(\'#wrap-map\').length==0 )return;\n            \n            var map = $("#wrap-map").gmap3({\n                get: { name:"map" }\n            });    \n            \n            var markers = [];\n\n            // Create the search box and link it to the UI element.\n            var input = /** @type {HTMLInputElement} */(\n              document.getElementById(\'pac-input\'));\n            map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);\n            \n            var searchBox = new google.maps.places.SearchBox(\n            /** @type {HTMLInputElement} */(input));\n            \n            // [START region_getplaces]\n            // Listen for the event fired when the user selects an item from the\n            // pick list. Retrieve the matching places for that item.\n            google.maps.event.addListener(searchBox, \'places_changed\', function() {\n            var places = searchBox.getPlaces();\n            \n            for (var i = 0, marker; marker = markers[i]; i++) {\n              marker.setMap(null);\n            }\n            \n            // For each place, get the icon, place name, and location.\n            markers = [];\n            var bounds = new google.maps.LatLngBounds();\n            for (var i = 0, place; place = places[i]; i++) {\n              var image = {\n                url: place.icon,\n                size: new google.maps.Size(71, 71),\n                origin: new google.maps.Point(0, 0),\n                anchor: new google.maps.Point(17, 34),\n                scaledSize: new google.maps.Size(25, 25)\n              };\n            \n              // Create a marker for each place.\n              var marker = new google.maps.Marker({\n                map: map,\n                icon: image,\n                title: place.name,\n                position: place.geometry.location\n              });\n            \n              markers.push(marker);\n            \n              bounds.extend(place.geometry.location);\n            }\n            \n            map.fitBounds(bounds);\n            var zoom = map.getZoom();\n            map.setZoom(zoom > zoomOnMapSearch ? zoomOnMapSearch : zoom);\n            });\n            // [END region_getplaces]\n            \n            if(myLocationEnabled){\n                // [START gmap mylocation]\n                \n                // Construct your control in whatever manner is appropriate.\n                // Generally, your constructor will want access to the\n                // DIV on which you\'ll attach the control UI to the Map.\n                var controlDiv = document.createElement(\'div\');\n                \n                // We don\'t really need to set an index value here, but\n                // this would be how you do it. Note that we set this\n                // value as a property of the DIV itself.\n                controlDiv.index = 1;\n                \n                // Add the control to the map at a designated control position\n                // by pushing it on the position\'s array. This code will\n                // implicitly add the control to the DOM, through the Map\n                // object. You should not attach the control manually.\n                map.controls[google.maps.ControlPosition.RIGHT_TOP].push(controlDiv);\n                \n                HomeControl(controlDiv, map)\n    \n                // [END gmap mylocation]\n            }\n            \n            if(rectangleSearchEnabled)\n            {\n                var controlDiv2 = document.createElement(\'div\');\n                controlDiv2.index = 2;\n                map.controls[google.maps.ControlPosition.RIGHT_TOP].push(controlDiv2);\n\t\t\t\t//start change\n\t\t\t\tvar controlDiv3 = document.createElement(\'div\');\n                controlDiv3.index = 2;\n                map.controls[google.maps.ControlPosition.RIGHT_TOP].push(controlDiv3);\n\t\t\t\t//end change\n                RectangleControl(controlDiv2, map,controlDiv3)\n            }\n            \n        }\n        function goUrl(element) {\n            var href = element.getAttribute(\'href\');\n            window.location.href = href;\n        }\n    </script>\n    <style>\n      .slick-prev, .slick-next {\n        width: 40px !important;\n        height: 40px !important;\n      }\n      .slick-prev:before, .slick-next:before {\n        font-size: 40px !important;\n        color: #000000 !important;\n      }\n      .aa-agent-social{\n        justify-content: center !important;\n      }\n      .aa-agent-social img{\n        margin: 0 !important;\n\n      }\n      .property_title{\n        font-size: 30px;\n        font-weight: 700;\n        line-height: 40px;\n        margin: 0;\n        color: #59abe3;\n        font-family: "Poppins", sans-serif;\n        text-align: center;\n        margin-bottom: 50px;\n      }\n      .aa-blog-single {\n          height: 500px !important;\n      }\n      @media (max-width: 991px) {\n        .aa-properties-item .aa-properties-item-img img {\n          height: 150px;\n        } \n      }\n      @media (max-width: 479px) {\n        .aa-properties-item .aa-properties-item-img img {\n          height: 250px;\n        } \n      }\n    </style>\n  </head>\n  <body class="aa-price-range">  \n  <!-- Pre Loader -->\n<div id="aa-preloader-area" >\n    <div class="pulse"></div>\n  </div>\n  <!-- SCROLL TOP BUTTON -->\n    <a class="scrollToTop" href=""><i class="fa fa-angle-double-up"></i></a>\n  <!-- END SCROLL TOP BUTTON -->\n  <!-- Start header section -->\n<header id="aa-header" style="background-color: #59abe3">  \n    <div class="container">\n      <div class="row">\n        <div class="col-md-12">\n          <div class="aa-header-area">\n            <div class="row">\n              <div class="col-md-6 col-sm-6 col-xs-6">\n                <div class="aa-header-left">\n                  <div class="aa-telephone-no">\n                    <span class="fa fa-phone"></span>\n                    09-261334475\n                  </div>\n                  <div class="aa-email hidden-xs">\n                    <span class="fa fa-envelope-o"></span> admin@property.com.mm\n                  </div>\n                </div>              \n              </div>\n              <div class="col-md-6 col-sm-6 col-xs-6">\n                  \n                <div class="aa-header-right">\n                  <a href="https://www.property.com.mm/index.php/frontend/editproperty/en" class="aa-login">List your property</a> <span class="aa-login">|</span>\n                  <a href="https://www.property.com.mm/index.php/frontend/login/en#content" class="aa-login" title="Login"> <i class="icon-off"></i> Login</a>\n                </div>\n                \n                \n                \n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </header>\n  <!-- End header section -->\n\n  <!-- Start menu section -->\n  <section id="aa-menu-area">\n    <nav class="navbar navbar-default main-navbar" role="navigation">  \n      <div class="container">\n        <div class="navbar-header">\n          <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->\n          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">\n            <span class="sr-only">Toggle navigation</span>\n            <span class="icon-bar"></span>\n            <span class="icon-bar"></span>\n            <span class="icon-bar"></span>\n          </button>\n          <!-- LOGO -->                                               \n          <!-- Text based logo -->\n           <a class="navbar-brand aa-logo" href="https://www.property.com.mm/index.php/en" title="Property.com.mm"> \n            <img src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/img/logo.png" id="logo" alt="Property.com.mm" title="Property.com.mm">\n           </a>\n           <!-- Image based logo -->\n           <!-- <a class="navbar-brand aa-logo-img" href="index.html"><img src="img/logo.png" alt="logo"></a> -->\n        </div>\n        <div id="navbar" class="navbar-collapse collapse">\n          <ul id="top-menu" class="nav navbar-nav navbar-right aa-main-nav">\n</li>\n</li>\n<li><a href="https://www.property.com.mm/index.php/en/192/developer" >Developer</a></li>\n<li><a href="https://www.property.com.mm/index.php/en/169/agents" >Agents</a></li>\n<li><a href="https://www.property.com.mm/index.php/en/147/featured" >Featured</a></li>\n</li>\n<li class="menuparent dropdown"><a class="dropdown-toggle" data-toggle="dropdown" onclick="goUrl(this)" href="https://www.property.com.mm/index.php/en/174/news" >News<b class="caret"></b></a>\n<ul class="dropdown-menu">\n<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=1#news" >Special Property Reports</a></li>\n<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=2#news" >International Property News</a></li>\n<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=3#news" >Regional News</a></li>\n<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=4#news" >Yangon Property News</a></li>\n<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=5#news" >Interviews</a></li>\n<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=6#news" >Market Analysis Reports</a></li>\n<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=7#news" >News By Property.com.mm Media Team</a></li>\n<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=8#news" >Articles By Property.com.mm Media Team</a></li>\n<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=9#news" >General Property News</a></li>\n</ul>\n</li>\n</li>\n<li class="menuparent dropdown"><a class="dropdown-toggle" data-toggle="dropdown" onclick="goUrl(this)" href="#" >Help<b class="caret"></b></a>\n<ul class="dropdown-menu">\n<li><a href="https://www.property.com.mm/index.php/en/help/14" >How To Create a new a

In [ ]:
soup=BeautifulSoup(c,'html.parser')
print(soup.prettify)

<bound method Tag.prettify of <!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Property.com.mm | Buy, Sell, Rent, Lease - Homepage - Find Commercial Industrial Residential Real Estate Property House Condo Land Warehouse Factory in Yangon Myanmar</title>
<!-- Autocomplete css -->
<!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css"> -->
<meta content="Property.com.mm makes your home searching in Myanmar a pleasant and expedited experience with thousands of listings with PICTURES and hundreds of agents in Yangon. Please call us now +95-09-440048448." name="description">
<meta content="Property.com.mm" name="keywords">
<meta content="" name="author">
<!-- <meta name="apple-itunes-app" content="app-id=544007664"> -->
<meta content="app-id=com.studioamk.pmm" name="google-play-app"/>
<meta content="https://www.property.com.mm/templates/bootstrap2-responsive/assets/img/logo-transparent-og.png" property="og:image">
<!-- Favicon -->
<link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/img/favicon.png" rel="shortcut icon" type="image/png"/>
<!-- Font awesome -->
<link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/font-awesome.css" rel="stylesheet"/>
<!-- Bootstrap -->
<link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/bootstrap.css" rel="stylesheet"/>
<!-- slick slider -->
<link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/slick.css" rel="stylesheet" type="text/css"/>
<!-- price picker slider -->
<link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/nouislider.css" rel="stylesheet" type="text/css"/>
<!-- Fancybox slider -->
<link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/jquery.fancybox.css" media="screen" rel="stylesheet" type="text/css">
<!-- Theme color -->
<link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/theme-color/default-theme.css" id="switcher" rel="stylesheet"/>
<!-- blueimp gallery -->
<link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/blueimp-gallery.min.css" rel="stylesheet" type="text/css"/>
<!-- Main style sheet -->
<link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/style.css" rel="stylesheet"/>
<link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/example/skitter.css" media="all" rel="stylesheet" type="text/css">
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Vollkorn" rel="stylesheet" type="text/css"/>
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css"/>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- jQuery library -->
<!-- Autocomplete js -->
<link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/jquery-ui.css" rel="stylesheet"/>
<script src="https://maps.google.com/maps/api/js?key=AIzaSyBSQyHRnuihlx2LpGrYwEACNg65AdqLOzs&amp;libraries=places,geometry&amp;language=en" type="text/javascript"></script>
<script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/jquery.min.js"></script>
<script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/jquery-ui.js"></script>
<link href="https://www.property.com.mm/templates/bootstrap2-responsive/assets/css/jquery.multiselect.css" rel="stylesheet">
<script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/jquery.multiselect.js"></script>
<script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/blueimp-gallery.min.js"></script>
<script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/gmap3.js"></script>
<!-- <script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/example/jquery-2.1.1.min.js"></script> -->
<script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/example/jquery.easing.1.3.js"></script>
<script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/example/jquery.skitter.min.js"></script>
<script src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/js/jquery.helpers.js"></script>
<!-- / Autocomplete js -->
<script>
        var timerMap;
        var ad_galleries;
        var firstSet = false;
        var mapRefresh = true;
        var loadOnTab = false;
        var zoomOnMapSearch = 9;
        var clusterConfig = null;
        var markerOptions = null;
        var mapDisableAutoPan = false;
        var mapStyle = null;
        var rent_inc_id = '55';
        var scrollWheelEnabled = false;
        var myLocationEnabled = true;
        var rectangleSearchEnabled = true;
        var c_mapTypeId = "style1"; // google.maps.MapTypeId.ROADMAP;
        // var c_mapTypeIds = ["style1",
        //                     google.maps.MapTypeId.ROADMAP,
        //                     google.maps.MapTypeId.HYBRID];

        $(document).ready(function() {
            $('.pagination.news a').click(function () {
                var page_num = $(this).attr('href');
                var n = page_num.lastIndexOf("/");
                page_num = page_num.substr(n+1);
                $.post($(this).attr('href'), {search: $('#search_showroom').val()}, function(data){
                    // $('.property_content_position').html(data.print);
                    document.querySelector('.property_content_position').innerHTML = data.print;
                    reloadElements();
                }, "json");

                return false;
            });
            $("#txtgoto").keyup(function(event){
				if(event.keyCode == 13){
					 var pageno = (parseInt($(this).val())-1)*9;
                manualSearch(pageno);
              return false;
				}

			});
        });
        function manualSearch(v_pagenum, scroll_enabled, onlysave)
        {
            if (typeof scroll_enabled === 'undefined') scroll_enabled = "#content";
            if (typeof onlysave === 'undefined') onlysave = false;
            var v_order = $('.selectpicker-small').val();
            var v_view = $('.view-type.active').attr('ref');
            var data = {
                order: v_order,
                view: v_view,
                page_num: v_pagenum
            };
            if($('#booking_date_from').length > 0)
            {
                if($('#booking_date_from').val() != '')
                    data['v_booking_date_from'] = $('#booking_date_from').val();
            }

            if($('#booking_date_to').length > 0)
            {
                if($('#booking_date_to').val() != '')
                    data['v_booking_date_to'] = $('#booking_date_to').val();
            }
        }
        function reloadElements()
        {
            // $('.selectpicker-small').selectpicker({
            //     style: 'btn-default'
            // });

            // $('.selectpicker-small').change(function() {
            //     manualSearch(0);
            //     return false;
            // });

            // $('.view-type').click(function () {
            //   $(this).parent().find('.view-type').removeClass("active");
            //   $(this).addClass("active");
            //   manualSearch(0);
            //   return false;
            // });

            // $('.pagination.properties a').click(function () {
            //   var page_num = $(this).attr('href');
            //   var n = page_num.lastIndexOf("/");
            //   page_num = page_num.substr(n+1);

            //   manualSearch(page_num);
            //   return false;
            // });
            // $("#txtgoto").keyup(function(event){
			// 	if(event.keyCode == 13){
			// 		/*if($( ".pagination.properties .pagination li:first a").html() == '&lt;'  || $( ".pagination.properties .pagination li:last a").html() == '&gt;')
			// 		{
			// 			var pageno = parseInt($(this).val())+1;
			// 			console.log(".pagination.properties .pagination li:nth-child("+pageno+") a");
			// 			$( ".pagination.properties .pagination li:nth-child("+pageno+") a" ).click();
			// 		}
			// 		else
			// 		{
			// 			$( ".pagination.properties .pagination li:nth-child("+$(this).val()+") a" ).click();
			// 		}
			// 		*/
			// 		 var pageno = (parseInt($(this).val())-1)*9;
            //     manualSearch(pageno);
            //   return false;
			// 	}

			// });
            $('.pagination.news a').click(function () {
                var page_num = $(this).attr('href');
                var n = page_num.lastIndexOf("/");
                page_num = page_num.substr(n+1);

                $.post($(this).attr('href'), {search: $('#search_showroom').val()}, function(data){
                    document.querySelector('.property_content_position').innerHTML = data.print;
                    reloadElements();
                }, "json");

                return false;
            });
        }
        function init_gmap_searchbox()
        {
            if( $('#pac-input').length==0 || $('#wrap-map').length==0 )return;

            var map = $("#wrap-map").gmap3({
                get: { name:"map" }
            });

            var markers = [];

            // Create the search box and link it to the UI element.
            var input = /** @type {HTMLInputElement} */(
              document.getElementById('pac-input'));
            map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

            var searchBox = new google.maps.places.SearchBox(
            /** @type {HTMLInputElement} */(input));

            // [START region_getplaces]
            // Listen for the event fired when the user selects an item from the
            // pick list. Retrieve the matching places for that item.
            google.maps.event.addListener(searchBox, 'places_changed', function() {
            var places = searchBox.getPlaces();

            for (var i = 0, marker; marker = markers[i]; i++) {
              marker.setMap(null);
            }

            // For each place, get the icon, place name, and location.
            markers = [];
            var bounds = new google.maps.LatLngBounds();
            for (var i = 0, place; place = places[i]; i++) {
              var image = {
                url: place.icon,
                size: new google.maps.Size(71, 71),
                origin: new google.maps.Point(0, 0),
                anchor: new google.maps.Point(17, 34),
                scaledSize: new google.maps.Size(25, 25)
              };

              // Create a marker for each place.
              var marker = new google.maps.Marker({
                map: map,
                icon: image,
                title: place.name,
                position: place.geometry.location
              });

              markers.push(marker);

              bounds.extend(place.geometry.location);
            }

            map.fitBounds(bounds);
            var zoom = map.getZoom();
            map.setZoom(zoom > zoomOnMapSearch ? zoomOnMapSearch : zoom);
            });
            // [END region_getplaces]

            if(myLocationEnabled){
                // [START gmap mylocation]

                // Construct your control in whatever manner is appropriate.
                // Generally, your constructor will want access to the
                // DIV on which you'll attach the control UI to the Map.
                var controlDiv = document.createElement('div');

                // We don't really need to set an index value here, but
                // this would be how you do it. Note that we set this
                // value as a property of the DIV itself.
                controlDiv.index = 1;

                // Add the control to the map at a designated control position
                // by pushing it on the position's array. This code will
                // implicitly add the control to the DOM, through the Map
                // object. You should not attach the control manually.
                map.controls[google.maps.ControlPosition.RIGHT_TOP].push(controlDiv);

                HomeControl(controlDiv, map)

                // [END gmap mylocation]
            }

            if(rectangleSearchEnabled)
            {
                var controlDiv2 = document.createElement('div');
                controlDiv2.index = 2;
                map.controls[google.maps.ControlPosition.RIGHT_TOP].push(controlDiv2);
				//start change
				var controlDiv3 = document.createElement('div');
                controlDiv3.index = 2;
                map.controls[google.maps.ControlPosition.RIGHT_TOP].push(controlDiv3);
				//end change
                RectangleControl(controlDiv2, map,controlDiv3)
            }

        }
        function goUrl(element) {
            var href = element.getAttribute('href');
            window.location.href = href;
        }
    </script>
<style>
      .slick-prev, .slick-next {
        width: 40px !important;
        height: 40px !important;
      }
      .slick-prev:before, .slick-next:before {
        font-size: 40px !important;
        color: #000000 !important;
      }
      .aa-agent-social{
        justify-content: center !important;
      }
      .aa-agent-social img{
        margin: 0 !important;

      }
      .property_title{
        font-size: 30px;
        font-weight: 700;
        line-height: 40px;
        margin: 0;
        color: #59abe3;
        font-family: "Poppins", sans-serif;
        text-align: center;
        margin-bottom: 50px;
      }
      .aa-blog-single {
          height: 500px !important;
      }
      @media (max-width: 991px) {
        .aa-properties-item .aa-properties-item-img img {
          height: 150px;
        }
      }
      @media (max-width: 479px) {
        .aa-properties-item .aa-properties-item-img img {
          height: 250px;
        }
      }
    </style>
</link></link></link></meta></meta></meta></meta></head>
<body class="aa-price-range">
<!-- Pre Loader -->
<div id="aa-preloader-area">
<div class="pulse"></div>
</div>
<!-- SCROLL TOP BUTTON -->
<a class="scrollToTop" href=""><i class="fa fa-angle-double-up"></i></a>
<!-- END SCROLL TOP BUTTON -->
<!-- Start header section -->
<header id="aa-header" style="background-color: #59abe3">
<div class="container">
<div class="row">
<div class="col-md-12">
<div class="aa-header-area">
<div class="row">
<div class="col-md-6 col-sm-6 col-xs-6">
<div class="aa-header-left">
<div class="aa-telephone-no">
<span class="fa fa-phone"></span>
                    09-261334475
                  </div>
<div class="aa-email hidden-xs">
<span class="fa fa-envelope-o"></span> admin@property.com.mm
                  </div>
</div>
</div>
<div class="col-md-6 col-sm-6 col-xs-6">
<div class="aa-header-right">
<a class="aa-login" href="https://www.property.com.mm/index.php/frontend/editproperty/en">List your property</a> <span class="aa-login">|</span>
<a class="aa-login" href="https://www.property.com.mm/index.php/frontend/login/en#content" title="Login"> <i class="icon-off"></i> Login</a>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</header>
<!-- End header section -->
<!-- Start menu section -->
<section id="aa-menu-area">
<nav class="navbar navbar-default main-navbar" role="navigation">
<div class="container">
<div class="navbar-header">
<!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggle collapsed" data-target="#navbar" data-toggle="collapse" type="button">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<!-- LOGO -->
<!-- Text based logo -->
<a class="navbar-brand aa-logo" href="https://www.property.com.mm/index.php/en" title="Property.com.mm">
<img alt="Property.com.mm" id="logo" src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/img/logo.png" title="Property.com.mm"/>
</a>
<!-- Image based logo -->
<!-- <a class="navbar-brand aa-logo-img" href="index.html"><img src="img/logo.png" alt="logo"></a> -->
</div>
<div class="navbar-collapse collapse" id="navbar">
<ul class="nav navbar-nav navbar-right aa-main-nav" id="top-menu">


<li><a href="https://www.property.com.mm/index.php/en/192/developer">Developer</a></li>
<li><a href="https://www.property.com.mm/index.php/en/169/agents">Agents</a></li>
<li><a href="https://www.property.com.mm/index.php/en/147/featured">Featured</a></li>

<li class="menuparent dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="https://www.property.com.mm/index.php/en/174/news" onclick="goUrl(this)">News<b class="caret"></b></a>
<ul class="dropdown-menu">
<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=1#news">Special Property Reports</a></li>
<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=2#news">International Property News</a></li>
<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=3#news">Regional News</a></li>
<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=4#news">Yangon Property News</a></li>
<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=5#news">Interviews</a></li>
<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=6#news">Market Analysis Reports</a></li>
<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=7#news">News By Property.com.mm Media Team</a></li>
<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=8#news">Articles By Property.com.mm Media Team</a></li>
<li><a href="https://www.property.com.mm/index.php/en/174/news?cat=9#news">General Property News</a></li>
</ul>
</li>

<li class="menuparent dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#" onclick="goUrl(this)">Help<b class="caret"></b></a>
<ul class="dropdown-menu">
<li><a href="https://www.property.com.mm/index.php/en/help/14">How To Create a new account    ?</a></li>
<li><a href="https://www.property.com.mm/index.php/en/help/5">How to post a new property ?</a></li>
<li><a href="https://www.property.com.mm/index.php/en/help/3">See All FAQs?</a></li>
</ul>
</li>







</ul>
<div class="simple-languages pull-right">
<ul><li class="en active"><a href="https://www.property.com.mm/index.php/en">en  <img alt="" src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/img/flags/en.png"/></a></li><li class="mm"><a href="https://www.property.com.mm/index.php/mm">mm  <img alt="" src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/img/flags/mm.png"/></a></li></ul>
</div>
</div><!--/.nav-collapse -->
</div>
</nav>
</section>
<!-- End menu section -->
<!-- Start slider  -->
<section id="aa-slider">
<div class="aa-slider-area">
<!-- Top slider -->
<div class="aa-top-slider">
<!-- Top slider single slide -->
<!-- -->
<!--  <div class="aa-top-slider-single">-->
<!--    <img src="https://www.property.com.mm/files/viber_image_2021_01_25_13_38_492021_01_2508_10_19.jpg" alt="Myanmar's No. 1 Property Website  - Apartments, Condos, Houses, Lands in Yangon and other Regions" title="Myanmar's No. 1 Property Website  - Apartments, Condos, Houses, Lands in Yangon and other Regions">-->
<!--  </div>-->
<!-- -->
<div class="aa-top-slider-single">
<img alt="Myanmar's No. 1 Property Website  - Apartments, Condos, Houses, Lands in Yangon and other Regions" src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/img/property_mm.jpeg" title="Myanmar's No. 1 Property Website  - Apartments, Condos, Houses, Lands in Yangon and other Regions"/>
</div>
<div class="aa-top-slider-single">

In [ ]:
# all=soup.find_all("div",{"class":"cl-gallery"})
all = soup.find_all("article", class_="aa-properties-item")

In [ ]:
all

[<article class="aa-properties-item aa-single-property">
 <div class="properties-img-height">
 <a "="" class="aa-properties-item-img" href="https://property.com.mm/index.php/property/5821/en/a_great_opportunity_for_those_who_want_to_live_in_a_luxury_house_near_inya_lake" title="A great opportunity for those who want to live in a luxury house near Inya Lake. in Mayangone, Yangon">
 <img alt="Features" src="https://property.com.mm/files/thumbnail/photo_2026_03_31_16_35_192026_03_3112_22_15.jpg"/>
 </a>
 </div>
 <div class="aa-tag for-sale">
                     Rent                  </div>
 <div class="cc-tag available">
                     available                  </div>
 <div class="aa-properties-item-content">
 <div class="row properties-content-height">
 <div class="col-md-12" style="height:45px;overflow:hidden;margin:10px 5px;">
 <p class="displayaddress"><strong title="A great opportunity for those who want to live in a luxury house near Inya Lake. in Mayangone, Yangon">A great opportunity for those who want to live in a luxury house near Inya Lake. in Mayangone, Yangon</strong>
 </p>
 </div>
 <div class="col-md-6">
 <p class="featured-option_2">Landed House</p>
 </div>
 <div class="col-md-6">
 <p class="featured-option_127">4950 sqft</p>
 </div>
 </div>
 <div class="aa-properties-info properties-info-height">
 <div class="row icon-wrapper">
 <div class="col-md-9">
 <span>  4<img alt="Total Rooms" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/room_ico.png" style="transform: perspective(2000px);" title="Total Rooms"/></span>
 <span>  0<img alt="Total Bedrooms" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/total_bed_room_ico.png" style="transform: perspective(2000px);" title="Total Bedrooms"/></span>
 </div>
 <div class="col-md-3">
 <img class="results-icon" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/icons/option_id/22.png" title="Air conditioning"/>
 </div>
 </div>
 </div>
 <div class="aa-properties-about properties-about-height">
 <div class="row">
 <div class="col-md-12">
 <a href="https://property.com.mm/index.php/property/5821/en/a_great_opportunity_for_those_who_want_to_live_in_a_luxury_house_near_inya_lake" title="latest properties">
 <p class="prop-description"><i>A great opportunity for those who want to live in a luxury house near Inya Lake.</i></p>
 </a>
 </div>
 </div>
 <div class="row" style="height:30px;">
 <div class="col-md-2">
 <img src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/user-agent.png" style="width:100%;" title="A1 Group Of Companines"/>
 </div>
 <div class="col-md-10">
 <span class="sm_agent" style="font-size:10px;">A1 Group Of Companines</span>
 </div>
 </div>
 </div>
 <div class="aa-properties-detial properties-detial-height">
 <span class="aa-price dtlprice" style="font-size:14px;">USD 5500 | </span>
 <span class="aa-price" style="font-size:14px;">Views: 47</span>
 <a class="aa-secondary-btn" href="https://property.com.mm/index.php/property/5821/en/a_great_opportunity_for_those_who_want_to_live_in_a_luxury_house_near_inya_lake" title="A great opportunity for those who want to live in a luxury house near Inya Lake. in Mayangone, Yangon">Details</a>
 </div>
 </div>
 </article>,
 <article class="aa-properties-item aa-single-property">
 <div class="properties-img-height">
 <a "="" class="aa-properties-item-img" href="https://property.com.mm/index.php/property/5820/en/house_for_rent_on_8_miles_of_country_road_suitable_for_family_living_and_also_suitable_for_opening_a_business_office" title="House for rent on 8 miles of country road, suitable for family living and also suitable for opening a business office. in Mayangone, Yangon">
 <img alt="Features" src="https://property.com.mm/files/thumbnail/photo_2026_03_31_16_06_132026_03_3112_01_18.jpg"/>
 </a>
 </div>
 <div class="aa-tag for-sale">
                     Rent                  </div>
 <div class="cc-tag available">
                     available                  </div>
 <div class="aa-properties-item-content">
 <div class="row properties-content-height">
 <div class="col-md-12" style="height:45px;overflow:hidden;margin:10px 5px;">
 <p class="displayaddress"><strong title="House for rent on 8 miles of country road, suitable for family living and also suitable for opening a business office. in Mayangone, Yangon">House for rent on 8 miles of country road, suitable for family living and also suitable for opening a business office. in Mayangone, Yangon</strong>
 </p>
 </div>
 <div class="col-md-6">
 <p class="featured-option_2">Landed House</p>
 </div>
 <div class="col-md-6">
 <p class="featured-option_127">6300 sqft</p>
 </div>
 </div>
 <div class="aa-properties-info properties-info-height">
 <div class="row icon-wrapper">
 <div class="col-md-9">
 <span>  5<img alt="Total Rooms" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/room_ico.png" style="transform: perspective(2000px);" title="Total Rooms"/></span>
 <span>  0<img alt="Total Bedrooms" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/total_bed_room_ico.png" style="transform: perspective(2000px);" title="Total Bedrooms"/></span>
 </div>
 <div class="col-md-3">
 </div>
 </div>
 </div>
 <div class="aa-properties-about properties-about-height">
 <div class="row">
 <div class="col-md-12">
 <a href="https://property.com.mm/index.php/property/5820/en/house_for_rent_on_8_miles_of_country_road_suitable_for_family_living_and_also_suitable_for_opening_a_business_office" title="latest properties">
 <p class="prop-description"><i>House for rent on 8 miles of country road, suitable for family living and also suitable…</i></p>
 </a>
 </div>
 </div>
 <div class="row" style="height:30px;">
 <div class="col-md-2">
 <img src="https://property.com.mm/files/thumbnail/26055892_1765624943470499_7873644043825661275_n2019_07_0613_24_35.jpg" style="width:100%;" title="Estate Myanmar Real Estate Agency"/>
 </div>
 <div class="col-md-10">
 <span class="sm_agent" style="font-size:10px;">Estate Myanmar Real Estate Agency</span>
 </div>
 </div>
 </div>
 <div class="aa-properties-detial properties-detial-height">
 <span class="aa-price dtlprice" style="font-size:14px;">40 Lkhs | </span>
 <span class="aa-price" style="font-size:14px;">Views: 56</span>
 <a class="aa-secondary-btn" href="https://property.com.mm/index.php/property/5820/en/house_for_rent_on_8_miles_of_country_road_suitable_for_family_living_and_also_suitable_for_opening_a_business_office" title="House for rent on 8 miles of country road, suitable for family living and also suitable for opening a business office. in Mayangone, Yangon">Details</a>
 </div>
 </div>
 </article>,
 <article class="aa-properties-item aa-single-property">
 <div class="properties-img-height">
 <a "="" class="aa-properties-item-img" href="https://property.com.mm/index.php/property/5819/en/between_merchant_street_and_mahabandula_road_suitable_for_business_ready_for_sale" title="Between Merchant Street and Mahabandula Road  Suitable for business, ready for sale in Kyauktada, Yangon">
 <img alt="Features" src="https://property.com.mm/files/thumbnail/photo_2026_02_10_17_41_392026_02_1111_10_36.jpg"/>
 </a>
 </div>
 <div class="aa-tag for-sale">
                     Sale                  </div>
 <div class="cc-tag available">
                     available                  </div>
 <div class="aa-properties-item-content">
 <div class="row properties-content-height">
 <div class="col-md-12" style="height:45px;overflow:hidden;margin:10px 5px;">
 <p class="displayaddress"><strong title="Between Merchant Street and Mahabandula Road  Suitable for business, ready for sale in Kyauktada, Yangon">Between Merchant Street and Mahabandula Road  Suitable for business, ready for sale in Kyauktada, Yangon</strong>
 </p>
 </div>
 <div class="col-md-6">
 <p class="featured-option_2">Flat</p>
 </div>
 <div class="col-md-6">
 <p class="featured-option_127">900 sqft</p>
 </div>
 </div>
 <div class="aa-properties-info properties-info-height">
 <div class="row icon-wrapper">
 <div class="col-md-9">
 <span>  0<img alt="Total Rooms" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/room_ico.png" style="transform: perspective(2000px);" title="Total Rooms"/></span>
 <span>  0<img alt="Total Bedrooms" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/total_bed_room_ico.png" style="transform: perspective(2000px);" title="Total Bedrooms"/></span>
 </div>
 <div class="col-md-3">
 </div>
 </div>
 </div>
 <div class="aa-properties-about properties-about-height">
 <div class="row">
 <div class="col-md-12">
 <a href="https://property.com.mm/index.php/property/5819/en/between_merchant_street_and_mahabandula_road_suitable_for_business_ready_for_sale" title="latest properties">
 <p class="prop-description"><i>Ready to sell in a busy and central location to create many good business opportunities</i></p>
 </a>
 </div>
 </div>
 <div class="row" style="height:30px;">
 <div class="col-md-2">
 <img src="https://property.com.mm/files/thumbnail/26055892_1765624943470499_7873644043825661275_n2019_07_0613_24_35.jpg" style="width:100%;" title="Estate Myanmar Real Estate Agency"/>
 </div>
 <div class="col-md-10">
 <span class="sm_agent" style="font-size:10px;">Estate Myanmar Real Estate Agency</span>
 </div>
 </div>
 </div>
 <div class="aa-properties-detial properties-detial-height">
 <span class="aa-price dtlprice" style="font-size:14px;">20000 Lkhs | </span>
 <span class="aa-price" style="font-size:14px;">Views: 156</span>
 <a class="aa-secondary-btn" href="https://property.com.mm/index.php/property/5819/en/between_merchant_street_and_mahabandula_road_suitable_for_business_ready_for_sale" title="Between Merchant Street and Mahabandula Road  Suitable for business, ready for sale in Kyauktada, Yangon">Details</a>
 </div>
 </div>
 </article>,
 <article class="aa-properties-item aa-single-property">
 <div class="properties-img-height">
 <a "="" class="aa-properties-item-img" href="https://property.com.mm/index.php/property/5817/en/for_sale_between_13th_and_monk_street_very_convenient_for_business" title="For sale between 13th and Monk Street, very convenient for business. in Lanmadaw, Yangon">
 <img alt="Features" src="https://property.com.mm/files/thumbnail/photo_2026_01_24_13_52_352026_01_2410_56_59.jpg"/>
 </a>
 </div>
 <div class="aa-tag for-sale">
                     Sale                  </div>
 <div class="cc-tag available">
                     available                  </div>
 <div class="aa-properties-item-content">
 <div class="row properties-content-height">
 <div class="col-md-12" style="height:45px;overflow:hidden;margin:10px 5px;">
 <p class="displayaddress"><strong title="For sale between 13th and Monk Street, very convenient for business. in Lanmadaw, Yangon">For sale between 13th and Monk Street, very convenient for business. in Lanmadaw, Yangon</strong>
 </p>
 </div>
 <div class="col-md-6">
 <p class="featured-option_2">Flat</p>
 </div>
 <div class="col-md-6">
 <p class="featured-option_127">675 sqft</p>
 </div>
 </div>
 <div class="aa-properties-info properties-info-height">
 <div class="row icon-wrapper">
 <div class="col-md-9">
 <span>  0<img alt="Total Rooms" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/room_ico.png" style="transform: perspective(2000px);" title="Total Rooms"/></span>
 <span>  0<img alt="Total Bedrooms" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/total_bed_room_ico.png" style="transform: perspective(2000px);" title="Total Bedrooms"/></span>
 </div>
 <div class="col-md-3">
 </div>
 </div>
 </div>
 <div class="aa-properties-about properties-about-height">
 <div class="row">
 <div class="col-md-12">
 <a href="https://property.com.mm/index.php/property/5817/en/for_sale_between_13th_and_monk_street_very_convenient_for_business" title="latest properties">
 <p class="prop-description"><i>Land sales in downtown Yangon create many good business opportunities</i></p>
 </a>
 </div>
 </div>
 <div class="row" style="height:30px;">
 <div class="col-md-2">
 <img src="https://property.com.mm/files/thumbnail/26055892_1765624943470499_7873644043825661275_n2019_07_0613_24_35.jpg" style="width:100%;" title="Estate Myanmar Real Estate Agency"/>
 </div>
 <div class="col-md-10">
 <span class="sm_agent" style="font-size:10px;">Estate Myanmar Real Estate Agency</span>
 </div>
 </div>
 </div>
 <div class="aa-properties-detial properties-detial-height">
 <span class="aa-price dtlprice" style="font-size:14px;">20000 Lkhs | </span>
 <span class="aa-price" style="font-size:14px;">Views: 135</span>
 <a class="aa-secondary-btn" href="https://property.com.mm/index.php/property/5817/en/for_sale_between_13th_and_monk_street_very_convenient_for_business" title="For sale between 13th and Monk Street, very convenient for business. in Lanmadaw, Yangon">Details</a>
 </div>
 </div>
 </article>,
 <article class="aa-properties-item aa-single-property">
 <div class="properties-img-height">
 <a "="" class="aa-properties-item-img" href="https://property.com.mm/index.php/property/5816/en/house_for_rent_near_moe_kaung_road_ideal_for_residential_school_or_office_use" title="House for rent near Moe Kaung Road, ideal for residential, school, or office use. in Yankin, Yangon">
 <img alt="Features" src="https://property.com.mm/files/thumbnail/photo_2026_01_09_11_08_002026_01_2410_51_56.jpg"/>
 </a>
 </div>
 <div class="aa-tag for-sale">
                     Rent                  </div>
 <div class="cc-tag available">
                     available                  </div>
 <div class="aa-properties-item-content">
 <div class="row properties-content-height">
 <div class="col-md-12" style="height:45px;overflow:hidden;margin:10px 5px;">
 <p class="displayaddress"><strong title="House for rent near Moe Kaung Road, ideal for residential, school, or office use. in Yankin, Yangon">House for rent near Moe Kaung Road, ideal for residential, school, or office use. in Yankin, Yangon</strong>
 </p>
 </div>
 <div class="col-md-6">
 <p class="featured-option_2">Landed House</p>
 </div>
 <div class="col-md-6">
 <p class="featured-option_127">5600 sqft</p>
 </div>
 </div>
 <div class="aa-properties-info properties-info-height">
 <div class="row icon-wrapper">
 <div class="col-md-9">
 <span>  7<img alt="Total Rooms" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/room_ico.png" style="transform: perspective(2000px);" title="Total Rooms"/></span>
 <span>  0<img alt="Total Bedrooms" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/total_bed_room_ico.png" style="transform: perspective(2000px);" title="Total Bedrooms"/></span>
 </div>
 <div class="col-md-3">
 <img class="results-icon" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/icons/option_id/32.png" title="Secure Car Parking"/>
 </div>
 </div>
 </div>
 <div class="aa-properties-about properties-about-height">
 <div class="row">
 <div class="col-md-12">
 <a href="https://property.com.mm/index.php/property/5816/en/house_for_rent_near_moe_kaung_road_ideal_for_residential_school_or_office_use" title="latest properties">
 <p class="prop-description"><i>House for rent near Moe Kaung Road, ideal for residential, school, or office use.</i></p>
 </a>
 </div>
 </div>
 <div class="row" style="height:30px;">
 <div class="col-md-2">
 <img src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/user-agent.png" style="width:100%;" title=""/>
 </div>
 <div class="col-md-10">
 <span class="sm_agent" style="font-size:10px;"></span>
 </div>
 </div>
 </div>
 <div class="aa-properties-detial properties-detial-height">
 <span class="aa-price dtlprice" style="font-size:14px;">80 Lkhs | </span>
 <span class="aa-price" style="font-size:14px;">Views: 127</span>
 <a class="aa-secondary-btn" href="https://property.com.mm/index.php/property/5816/en/house_for_rent_near_moe_kaung_road_ideal_for_residential_school_or_office_use" title="House for rent near Moe Kaung Road, ideal for residential, school, or office use. in Yankin, Yangon">Details</a>
 </div>
 </div>
 </article>,
 <article class="aa-properties-item aa-single-property">
 <div class="properties-img-height">
 <a "="" class="aa-properties-item-img" href="https://property.com.mm/index.php/property/5815/en/the_lake_suite_condo_for_rent_on_kamaba_aye_pagoda_road" title="The Lake Suite Condo for rent on Kamaba Aye Pagoda Road in Mayangone, Yangon">
 <img alt="Features" src="https://property.com.mm/files/thumbnail/photo_2026_01_09_10_04_232026_01_2410_46_22.jpg"/>
 </a>
 </div>
 <div class="aa-tag for-sale">
                     Rent                  </div>
 <div class="cc-tag available">
                     available                  </div>
 <div class="aa-properties-item-content">
 <div class="row properties-content-height">
 <div class="col-md-12" style="height:45px;overflow:hidden;margin:10px 5px;">
 <p class="displayaddress"><strong title="The Lake Suite Condo for rent on Kamaba Aye Pagoda Road in Mayangone, Yangon">The Lake Suite Condo for rent on Kamaba Aye Pagoda Road in Mayangone, Yangon</strong>
 </p>
 </div>
 <div class="col-md-6">
 <p class="featured-option_2">Flat</p>
 </div>
 <div class="col-md-6">
 <p class="featured-option_127">1280 sqft</p>
 </div>
 </div>
 <div class="aa-properties-info properties-info-height">
 <div class="row icon-wrapper">
 <div class="col-md-9">
 <span>  3<img alt="Total Rooms" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/room_ico.png" style="transform: perspective(2000px);" title="Total Rooms"/></span>
 <span>  2<img alt="Total Bedrooms" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/total_bed_room_ico.png" style="transform: perspective(2000px);" title="Total Bedrooms"/></span>
 </div>
 <div class="col-md-3">
 <img class="results-icon" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/icons/option_id/22.png" title="Air conditioning"/>
 <img class="results-icon" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/icons/option_id/25.png" title="Washing Machine"/>
 <img class="results-icon" src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/icons/option_id/32.png" title="Secure Car Parking"/>
 </div>
 </div>
 </div>
 <div class="aa-properties-about properties-about-height">
 <div class="row">
 <div class="col-md-12">
 <a href="https://property.com.mm/index.php/property/5815/en/the_lake_suite_condo_for_rent_on_kamaba_aye_pagoda_road" title="latest properties">
 <p class="prop-description"><i>The Lake Suite Condo for rent</i></p>
 </a>
 </div>
 </div>
 <div class="row" style="height:30px;">
 <div class="col-md-2">
 <img src="https://property.com.mm/templates/bootstrap2-responsive/assets/img/user-agent.png" style="width:100%;" title="A1 Group Of Companines"/>
 </div>
 <div class="col-md-10">
 <span class="sm_agent" style="font-size:10px;">A1 Group Of Companines</span>
 </div>
 </div>
 </div>
 <div class="aa-properties-detial properties-detial-height">
 <span class="aa-price dtlprice" style="font-size:14px;">40 Lkhs | </span>
 <span class="aa-price" style="font-size:14px;">Views: 147</span>
 <a class="aa-secondary-btn" href="https://property.com.mm/index.php/property/5815/en/the_lake_suite_condo_for_rent_on_kamaba_aye_pagoda_road" title="The Lake Suite Condo for rent on Kamaba Aye Pagoda Road in Mayangone, Yangon">Details</a>
 </div>
 </div>
 </article>,
 <article class="aa-properties-item aa-single-property">
 <div class="properties-img-height">
 <a "="" class="aa-properties-item-img" href="https://property.com.mm/index.php/property/5814/en/near_u_wisara_road_north_dagon_township" title="Near U Wisara Road, North Dagon Township in Dagon Myothit (north), Yangon">
 <img alt="Features" src="https://property.com.mm/files/thumbnail/photo_2025_09_15_11_39_562025_09_1507_50_28.jpg"/>
 </a>
 </div>

In [ ]:
len(all)

9

In [ ]:
all[0].find_all("p",{"class":"displayaddress"})

[<p class="displayaddress"><strong title="A great opportunity for those who want to live in a luxury house near Inya Lake. in Mayangone, Yangon">A great opportunity for those who want to live in a luxury house near Inya Lake. in Mayangone, Yangon</strong>
 </p>,
 <p class="displayaddress"><strong title="House for rent on 8 miles of country road, suitable for family living and also suitable for opening a business office. in Mayangone, Yangon">House for rent on 8 miles of country road, suitable for family living and also suitable for opening a business office. in Mayangone, Yangon</strong>
 </p>,
 <p class="displayaddress"><strong title="Between Merchant Street and Mahabandula Road  Suitable for business, ready for sale in Kyauktada, Yangon">Between Merchant Street and Mahabandula Road  Suitable for business, ready for sale in Kyauktada, Yangon</strong>
 </p>,
 <p class="displayaddress"><strong title="For sale between 13th and Monk Street, very convenient for business. in Lanmadaw, Yangon">For sale between 13th and Monk Street, very convenient for business. in Lanmadaw, Yangon</strong>
 </p>,
 <p class="displayaddress"><strong title="House for rent near Moe Kaung Road, ideal for residential, school, or office use. in Yankin, Yangon">House for rent near Moe Kaung Road, ideal for residential, school, or office use. in Yankin, Yangon</strong>
 </p>,
 <p class="displayaddress"><strong title="The Lake Suite Condo for rent on Kamaba Aye Pagoda Road in Mayangone, Yangon">The Lake Suite Condo for rent on Kamaba Aye Pagoda Road in Mayangone, Yangon</strong>
 </p>,
 <p class="displayaddress"><strong title="Near U Wisara Road, North Dagon Township in Dagon Myothit (north), Yangon">Near U Wisara Road, North Dagon Township in Dagon Myothit (north), Yangon</strong>
 </p>,
 <p class="displayaddress"><strong title="Bahan Township, U Wisara Road in Bahan, Yangon">Bahan Township, U Wisara Road in Bahan, Yangon</strong>
 </p>,
 <p class="displayaddress"><strong title="Land for sale with building ready for Hotel / Motel / Guesthouse business in Dagon Myothit (south), Yangon">Land for sale with building ready for Hotel / Motel / Guesthouse business in Dagon Myothit (south), Yangon</strong>
 </p>]

In [ ]:
all[0].find("p",{"class":"displayaddress"}).text.replace("\n","")

'Flat For Rent in Thamain Bayan Road, Tamwe, Yangon'

In [ ]:
all[2].find("span",{'class','aa-price'}).text

'50 Lkhs'

In [ ]:
all[2].find("p",{'class','featured-option_2'}).text

'Landed House'

In [ ]:
print(item.prettify())

<article class="aa-properties-item aa-single-property">
 <a class="aa-properties-item-img" href="https://www.property.com.mm/index.php/property/5723/en/flat_for_rent" title="latest properties">
  <img alt="Features" src="https://www.property.com.mm/files/thumbnail/8f14e45fceea167a5a36dedd4bea252024_01_3109_32_52.jpg"/>
 </a>
 <div class="aa-tag for-sale">
  Sale
 </div>
 <div class="bb-tag available">
  available
 </div>
 <div class="aa-properties-item-content">
  <div class="row" style="margin-top:5px;">
   <div class="col-md-6">
    <p class="featured-option_2">
     New Flat
    </p>
   </div>
   <div class="col-md-6">
    <p class="featured-option_127">
     500 sqft
    </p>
   </div>
  </div>
  <div class="aa-properties-info">
   <div class="row icon-wrapper">
    <div class="col-md-6">
     <span>
      1
      <img alt="Total Rooms" src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/img/room_ico.png" style="transform: perspective(2000px);" title="Total Rooms"/>
     </span>
     <span>
      0
      <img alt="Total Bedrooms" src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/img/total_bed_room_ico.png" style="transform: perspective(2000px);" title="Total Bedrooms"/>
     </span>
    </div>
    <div class="col-md-6" style="display:flex; justify-content: end;">
     <img class="results-icon" src="https://www.property.com.mm/templates/bootstrap2-responsive/assets/img/icons/option_id/19.png" title="Bathrooms"/>
    </div>
   </div>
  </div>
  <div class="aa-properties-about">
   <div class="row">
    <div class="col-md-12 col-sm-12">
     <a href="https://www.property.com.mm/index.php/property/5723/en/flat_for_rent" title="latest properties">
      <p class="displayaddress">
       <strong title="Flat For Rent in Near by Barrkayar Road, Sanchaung, Yangon">
        Flat For Rent in Near by Barrkayar Road, Sanchaung, Yangon
       </strong>
      </p>
     </a>
    </div>
   </div>
   <div class="row" style="height:30px;">
    <div class="col-xs-2">
     <img src="" style="width:31px; height:31px;" title=""/>
    </div>
    <div class="col-xs-10">
     <span class="sm_agent" style="font-size:10px;">
     </span>
    </div>
   </div>
  </div>
  <div class="aa-properties-detial">
   <span class="aa-price">
    1700 Lkhs
   </span>
   <a class="aa-secondary-btn" href="https://www.property.com.mm/index.php/property/5723/en/flat_for_rent" title="Flat For Rent in Near by Barrkayar Road, Sanchaung, Yangon">
    Details
   </a>
  </div>
 </div>
</article>

In [ ]:
l=[]
base_url="https://property.com.mm/index.php/en/6/browse"
for page in range(0,60,10):
  url=base_url+str(page)
  print("Scraping:",url)

  r=requests.get(url)
  c=r.content
  soup=BeautifulSoup(c,"html.parser")

  all=soup.find_all("article", class_="aa-properties-item")
  print("Listings on this page:",len(all))

  for item in all:
    d={}
    try:
         price_tag = item.find("span", class_="aa-price")
         d["Price"] = price_tag.text.strip() if price_tag else "N/A"

         address_tag = item.find("p", class_="displayaddress")
         d["Address"] = address_tag.text.strip() if address_tag else "N/A"

         type_tag = item.find("p", class_="featured-option_2")
         d["Type"] = type_tag.text.strip() if type_tag else "N/A"


         room_icon=item.find("img",alt="Total Rooms")
         d['Rooms']=room_icon.parent.text.strip() if room_icon else "0"

         bed_icon = item.find("img", alt="Total Bedrooms")
         d["Bedrooms"] = bed_icon.parent.text.strip() if bed_icon else "0"


         l.append(d)
    except Exception as e:
      continue

  print(f"Total Listing collected:{len(l)}")

Scraping: https://property.com.mm/index.php/en/6/browse0
Listings on this page: 9
Total Listing collected:9
Scraping: https://property.com.mm/index.php/en/6/browse10
Listings on this page: 9
Total Listing collected:18
Scraping: https://property.com.mm/index.php/en/6/browse20
Listings on this page: 9
Total Listing collected:27
Scraping: https://property.com.mm/index.php/en/6/browse30
Listings on this page: 9
Total Listing collected:36
Scraping: https://property.com.mm/index.php/en/6/browse40
Listings on this page: 9
Total Listing collected:45
Scraping: https://property.com.mm/index.php/en/6/browse50
Listings on this page: 9
Total Listing collected:54

In [ ]:
import pandas
df=pandas.DataFrame(l)

In [ ]:
df

,Price,Address,Type,Rooms,Bedrooms
0,USD 5500 |,A great opportunity for those who want to live...,Landed House,4,0
1,40 Lkhs |,"House for rent on 8 miles of country road, sui...",Landed House,5,0
2,20000 Lkhs |,Between Merchant Street and Mahabandula Road ...,Flat,0,0
3,20000 Lkhs |,"For sale between 13th and Monk Street, very co...",Flat,0,0
4,80 Lkhs |,"House for rent near Moe Kaung Road, ideal for ...",Landed House,7,0
5,40 Lkhs |,The Lake Suite Condo for rent on Kamaba Aye Pa...,Flat,3,2
6,40000 Lkhs |,"Near U Wisara Road, North Dagon Township in Da...",Landed House,20,0
7,40000 Lkhs |,"Bahan Township, U Wisara Road in Bahan, Yangon",Landed House,16,0
8,39800 Lkhs |,Land for sale with building ready for Hotel / ...,Landed House,16,0
9,USD 5500 |,A great opportunity for those who want to live...,Landed House,4,0
10,40 Lkhs |,"House for rent on 8 miles of country road, sui...",Landed House,5,0
11,20000 Lkhs |,Between Merchant Street and Mahabandula Road ...,Flat,0,0
12,20000 Lkhs |,"For sale between 13th and Monk Street, very co...",Flat,0,0
13,80 Lkhs |,"House for rent near Moe Kaung Road, ideal for ...",Landed House,7,0
14,40 Lkhs |,The Lake Suite Condo for rent on Kamaba Aye Pa...,Flat,3,2
15,40000 Lkhs |,"Near U Wisara Road, North Dagon Township in Da...",Landed House,20,0
16,40000 Lkhs |,"Bahan Township, U Wisara Road in Bahan, Yangon",Landed House,16,0
17,39800 Lkhs |,Land for sale with building ready for Hotel / ...,Landed House,16,0
18,USD 5500 |,A great opportunity for those who want to live...,Landed House,4,0
19,40 Lkhs |,"House for rent on 8 miles of country road, sui...",Landed House,5,0
20,20000 Lkhs |,Between Merchant Street and Mahabandula Road ...,Flat,0,0
21,20000 Lkhs |,"For sale between 13th and Monk Street, very co...",Flat,0,0
22,80 Lkhs |,"House for rent near Moe Kaung Road, ideal for ...",Landed House,7,0
23,40 Lkhs |,The Lake Suite Condo for rent on Kamaba Aye Pa...,Flat,3,2
24,40000 Lkhs |,"Near U Wisara Road, North Dagon Township in Da...",Landed House,20,0
25,40000 Lkhs |,"Bahan Township, U Wisara Road in Bahan, Yangon",Landed House,16,0
26,39800 Lkhs |,Land for sale with building ready for Hotel / ...,Landed House,16,0
27,USD 5500 |,A great opportunity for those who want to live...,Landed House,4,0
28,40 Lkhs |,"House for rent on 8 miles of country road, sui...",Landed House,5,0
29,20000 Lkhs |,Between Merchant Street and Mahabandula Road ...,Flat,0,0
30,20000 Lkhs |,"For sale between 13th and Monk Street, very co...",Flat,0,0
31,80 Lkhs |,"House for rent near Moe Kaung Road, ideal for ...",Landed House,7,0
32,40 Lkhs |,The Lake Suite Condo for rent on Kamaba Aye Pa...,Flat,3,2
33,40000 Lkhs |,"Near U Wisara Road, North Dagon Township in Da...",Landed House,20,0
34,40000 Lkhs |,"Bahan Township, U Wisara Road in Bahan, Yangon",Landed House,16,0
35,39800 Lkhs |,Land for sale with building ready for Hotel / ...,Landed House,16,0
36,USD 5500 |,A great opportunity for those who want to live...,Landed House,4,0
37,40 Lkhs |,"House for rent on 8 miles of country road, sui...",Landed House,5,0
38,20000 Lkhs |,Between Merchant Street and Mahabandula Road ...,Flat,0,0
39,20000 Lkhs |,"For sale between 13th and Monk Street, very co...",Flat,0,0
40,80 Lkhs |,"House for rent near Moe Kaung Road, ideal for ...",Landed House,7,0
41,40 Lkhs |,The Lake Suite Condo for rent on Kamaba Aye Pa...,Flat,3,2
42,40000 Lkhs |,"Near U Wisara Road, North Dagon Township in Da...",Landed House,20,0
43,40000 Lkhs |,"Bahan Township, U Wisara Road in Bahan, Yangon",Landed House,16,0
44,39800 Lkhs |,Land for sale with building ready for Hotel / ...,Landed House,16,0
45,USD 5500 |,A great opportunity for those who want to live...,Landed House,4,0
46,40 Lkhs |,"House for rent on 8 miles of country road, sui...",Landed House,5,0
47,20000 Lkhs |,Between Merchant Street and Mahabandula Road ...,Flat,0,0
48,20000 Lkhs |,"For sale between 13th and Monk Street, very co...",Flat,0,0
49,80 Lkhs |,"House for rent near Moe Kaung Road, ideal for ...",Landed House,7,0
50,40 Lkhs |,The Lake Suite Condo for rent on Kamaba Aye Pa...,Flat,3,2
51,40000 Lkhs |,"Near U Wisara Road, North Dagon Township in Da...",Landed House,20,0
52,40000 Lkhs |,"Bahan Township, U Wisara Road in Bahan, Yangon",Landed House,16,0
53,39800 Lkhs |,Land for sale with building ready for Hotel / ...,Landed House,16,0

In [ ]:
base_url="https://property.com.mm/index.php/en/6/browse"
for page in range(0,60,10):
  print(base_url+str(page))
  # r=requests.get(base_url+str(page))
  # c=r.content
  # soup=BeautifulSoup(c,"html.parser")
  # print(soup.prettify)

https://property.com.mm/index.php/en/6/browse0
https://property.com.mm/index.php/en/6/browse10
https://property.com.mm/index.php/en/6/browse20
https://property.com.mm/index.php/en/6/browse30
https://property.com.mm/index.php/en/6/browse40
https://property.com.mm/index.php/en/6/browse50

In [ ]:
df.to_csv("output.csv")

In [ ]:
import pandas as pd
df=pd.read_csv("output.csv")
df.head()

,Unnamed: 0,Price,Address,Type,Rooms,Bedrooms
0,0,USD 5500 |,A great opportunity for those who want to live...,Landed House,4,0
1,1,40 Lkhs |,"House for rent on 8 miles of country road, sui...",Landed House,5,0
2,2,20000 Lkhs |,Between Merchant Street and Mahabandula Road ...,Flat,0,0
3,3,20000 Lkhs |,"For sale between 13th and Monk Street, very co...",Flat,0,0
4,4,80 Lkhs |,"House for rent near Moe Kaung Road, ideal for ...",Landed House,7,0

#Clean Data

In [ ]:
import pandas as pd
import re

def parse_price(price):
    if pd.isna(price):
        return pd.Series([None, None])

    price = str(price).replace("|", "").strip()

    if "USD" in price:
        currency = "USD"
        number = re.findall(r"\d+(?:\.\d+)?", price)
        value = float(number[0]) if number else None

    elif "Lkhs" in price:
        currency = "Lkhs"
        number = re.findall(r"\d+(?:\.\d+)?", price)
        value = float(number[0]) if number else None

    else:
        currency = "Unknown"
        number = re.findall(r"\d+(?:\.\d+)?", price)
        value = float(number[0]) if number else None

    return pd.Series([currency, value])

df[["Currency", "Price_Value"]] = df["Price"].apply(parse_price)

In [ ]:
print(df[["Price", "Currency", "Price_Value"]].head())

          Price Currency  Price_Value
0    USD 5500 |      USD       5500.0
1     40 Lkhs |     Lkhs         40.0
2  20000 Lkhs |     Lkhs      20000.0
3  20000 Lkhs |     Lkhs      20000.0
4     80 Lkhs |     Lkhs         80.0

## Currency

In [ ]:
# Step 1: Clean raw string
df["Price_Clean"] = df["Price"].astype(str).str.replace("|", "", regex=False).str.strip()

# Step 2: Extract currency FIRST
df["Currency"] = df["Price_Clean"].apply(
    lambda x: "USD" if "USD" in str(x)
    else "Lkhs" if "Lkhs" in str(x)
    else "Unknown"
)

# Step 3: Extract numeric value
df["Price_Value"] = df["Price_Clean"].str.extract(r"(\d+(?:\.\d+)?)").astype(float)

In [ ]:
print(df["Price"].head())
print(df["Price"].dtype)

0      192.5
1       40.0
2    20000.0
3    20000.0
4       80.0
Name: Price, dtype: float64
float64

In [ ]:
df = pd.read_csv("output.csv")

In [ ]:
import pandas as pd

df = pd.read_csv("output.csv")

df["Price_Raw"] = df["Price"].astype(str)
df["Price_Clean"] = df["Price_Raw"].str.replace("|", "", regex=False).str.strip()

df["Currency"] = df["Price_Clean"].apply(
    lambda x: "USD" if "USD" in x
    else "Lkhs" if "Lkhs" in x
    else "Unknown"
)

df["Price_Value"] = df["Price_Clean"].str.extract(r"(\d+(?:\.\d+)?)").astype(float)

print(df[["Price", "Price_Clean", "Currency", "Price_Value"]].head())

          Price Price_Clean Currency  Price_Value
0    USD 5500 |    USD 5500      USD       5500.0
1     40 Lkhs |     40 Lkhs     Lkhs         40.0
2  20000 Lkhs |  20000 Lkhs     Lkhs      20000.0
3  20000 Lkhs |  20000 Lkhs     Lkhs      20000.0
4     80 Lkhs |     80 Lkhs     Lkhs         80.0

## Convert to One Currency

In [ ]:
import numpy as np
USD_TO_LKHS = 2100 / 100000  # example: convert USD → Lkhs (adjust if needed)

df["Price_Lkhs"] = np.where(
    df["Currency"] == "USD",
    df["Price_Value"] * USD_TO_LKHS,
    df["Price_Value"]
)

##Check data quality

In [ ]:
print(df.info())
print(df.isnull().sum())
print(df["Currency"].value_counts())
print(df["Type"].value_counts())
print(df["Bedrooms"].value_counts())
print(df["Rooms"].value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0.1   54 non-null     int64
 1   Unnamed: 0     54 non-null     int64
 2   Price          54 non-null     object
 3   Address        54 non-null     object
 4   Type           54 non-null     object
 5   Rooms          54 non-null     int64
 6   Bedrooms       54 non-null     int64
 7   Price_Numeric  54 non-null     float64
 8   Price_Raw      54 non-null     object
 9   Price_Clean    54 non-null     object
 10  Currency       54 non-null     object
 11  Price_Value    54 non-null     float64
dtypes: float64(2), int64(4), object(6)
memory usage: 5.2+ KB
None
Unnamed: 0.1     0
Unnamed: 0       0
Price            0
Address          0
Type             0
Rooms            0
Bedrooms         0
Price_Numeric    0
Price_Raw        0
Price_Clean      0
Currency         0
Price_Value      0
dtype: int64
Currency
Lkhs    48
USD      6
Name: count, dtype: int64
Type
Landed House    36
Flat            18
Name: count, dtype: int64
Bedrooms
0    48
2     6
Name: count, dtype: int64
Rooms
0     12
16    12
4      6
5      6
7      6
3      6
20     6
Name: count, dtype: int64

In [ ]:
df[df["Price_Value"].isnull()]
df[df["Bedrooms"] == 0].head(10)

,Unnamed: 0.1,Unnamed: 0,Price,Address,Type,Rooms,Bedrooms,Price_Numeric,Price_Raw,Price_Clean,Currency,Price_Value
0,0,0,USD 5500 |,A great opportunity for those who want to live...,Landed House,4,0,1.925000e+07,USD 5500 |,USD 5500,USD,5500.0
1,1,1,40 Lkhs |,"House for rent on 8 miles of country road, sui...",Landed House,5,0,4.000000e+06,40 Lkhs |,40 Lkhs,Lkhs,40.0
2,2,2,20000 Lkhs |,Between Merchant Street and Mahabandula Road ...,Flat,0,0,2.000000e+09,20000 Lkhs |,20000 Lkhs,Lkhs,20000.0
3,3,3,20000 Lkhs |,"For sale between 13th and Monk Street, very co...",Flat,0,0,2.000000e+09,20000 Lkhs |,20000 Lkhs,Lkhs,20000.0
4,4,4,80 Lkhs |,"House for rent near Moe Kaung Road, ideal for ...",Landed House,7,0,8.000000e+06,80 Lkhs |,80 Lkhs,Lkhs,80.0
6,6,6,40000 Lkhs |,"Near U Wisara Road, North Dagon Township in Da...",Landed House,20,0,4.000000e+09,40000 Lkhs |,40000 Lkhs,Lkhs,40000.0
7,7,7,40000 Lkhs |,"Bahan Township, U Wisara Road in Bahan, Yangon",Landed House,16,0,4.000000e+09,40000 Lkhs |,40000 Lkhs,Lkhs,40000.0
8,8,8,39800 Lkhs |,Land for sale with building ready for Hotel / ...,Landed House,16,0,3.980000e+09,39800 Lkhs |,39800 Lkhs,Lkhs,39800.0
9,9,9,USD 5500 |,A great opportunity for those who want to live...,Landed House,4,0,1.925000e+07,USD 5500 |,USD 5500,USD,5500.0
10,10,10,40 Lkhs |,"House for rent on 8 miles of country road, sui...",Landed House,5,0,4.000000e+06,40 Lkhs |,40 Lkhs,Lkhs,40.0

In [ ]:
df_usd = df[df["Currency"] == "USD"].copy()
df_lkhs = df[df["Currency"] == "Lkhs"].copy()

In [ ]:
print(df_usd[["Price", "Price_Value"]].head())
print(df_lkhs[["Price", "Price_Value"]].head())

         Price  Price_Value
0   USD 5500 |       5500.0
9   USD 5500 |       5500.0
18  USD 5500 |       5500.0
27  USD 5500 |       5500.0
36  USD 5500 |       5500.0
          Price  Price_Value
1     40 Lkhs |         40.0
2  20000 Lkhs |      20000.0
3  20000 Lkhs |      20000.0
4     80 Lkhs |         80.0
5     40 Lkhs |         40.0

##clean Rooms and Bedrooms

In [ ]:
df["Rooms"] = pd.to_numeric(df["Rooms"], errors="coerce")
df["Bedrooms"] = pd.to_numeric(df["Bedrooms"], errors="coerce")

Handle Missing

In [ ]:
df["Rooms"].fillna(df["Rooms"].median(), inplace=True)
df["Bedrooms"].fillna(df["Bedrooms"].median(), inplace=True)

/tmp/ipykernel_1384/1733572831.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Rooms"].fillna(df["Rooms"].median(), inplace=True)
/tmp/ipykernel_1384/1733572831.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Bedrooms"].fillna(df["Bedrooms"].median(), inplace=True)

In [ ]:
print(df[["Rooms", "Bedrooms"]].describe())

           Rooms   Bedrooms
count  54.000000  54.000000
mean    7.888889   0.222222
std     7.144510   0.634441
min     0.000000   0.000000
25%     3.000000   0.000000
50%     5.000000   0.000000
75%    16.000000   0.000000
max    20.000000   2.000000

## Clean Categorical columns

In [ ]:
df["Type"] = df["Type"].str.strip().fillna("Unknown")

In [ ]:
df = pd.get_dummies(df, columns=["Type"], drop_first=True)

Remove Useless columns

In [ ]:
df_clean = df[[
    "Price_Lkhs",
    "Rooms",
    "Bedrooms"
] + [col for col in df.columns if col.startswith("Type_")]]

Handle Outliers for ML

In [ ]:
df_clean = df_clean[df_clean["Price_Lkhs"] < df_clean["Price_Lkhs"].quantile(0.99)]

In [ ]:
for col in df_clean.columns:
    if df_clean[col].dtype == 'bool':
        df_clean[col] = df_clean[col].astype(int)

Final Check

In [ ]:
print(df_clean.info())
print(df_clean.describe())
print(df_clean.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
Index: 42 entries, 0 to 53
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Price_Lkhs         42 non-null     float64
 1   Rooms              42 non-null     int64
 2   Bedrooms           42 non-null     int64
 3   Type_Landed House  42 non-null     int64
dtypes: float64(1), int64(3)
memory usage: 1.6 KB
None
         Price_Lkhs      Rooms   Bedrooms  Type_Landed House
count     42.000000  42.000000  42.000000          42.000000
mean   11439.357143   5.000000   0.285714           0.571429
std    14657.308328   5.132394   0.708338           0.500870
min       40.000000   0.000000   0.000000           0.000000
25%       40.000000   0.000000   0.000000           0.000000
50%      115.500000   4.000000   0.000000           1.000000
75%    20000.000000   7.000000   0.000000           1.000000
max    39800.000000  16.000000   2.000000           1.000000
Price_Lkhs           0
Rooms                0
Bedrooms             0
Type_Landed House    0
dtype: int64

In [ ]:
df_clean.to_csv("ml_ready_properties.csv", index=False)